<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="aznevmper-3845" failures="1" tests="4" name="Default test" time="0.2" errors="0" timestamp="2024-01-11T14:03:55 GMT">
  <testcase classname="TestNG.TestNGLearning" name="TestNGSample" time="0.025"/>
  <testcase classname="TestNG.TestNGLearning" name="TestNGSample" time="0.005"/>
  <testcase classname="TestNG.TestNGLearning" name="TestNGSample" time="0.005"/>
  <testcase classname="TestNG.TestNGLearning" name="TestNGSample2" time="0.07">
    <failure type="org.testng.TestException" message="
Method TestNGLearning.TestNGSample2()[pri:1, instance:TestNG.TestNGLearning@3d6f0054] should have thrown an exception of type class java.util.concurrent.TimeoutException">
      <![CDATA[org.testng.TestException: 
Method TestNGLearning.TestNGSample2()[pri:1, instance:TestNG.TestNGLearning@3d6f0054] should have thrown an exception of type class java.util.concurrent.TimeoutException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestNGSample2 -->
</testsuite> <!-- Default test -->
